"""Create mentor bookings table

Revision ID: 55065832fc2a
Revises: 7ab1789d5ea7
Create Date: 2026-08-15 22:06:18.841403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55065832fc2a'
down_revision = '7ab1789d5ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_name', sa.String(length=150), nullable=False),
    sa.Column('mentor_email', sa.String(length=200), nullable=False),
    sa.Column('student_name', sa.String(length=150), nullable=False),
    sa.Column('student_email', sa.String(length=200), nullable=False),
    sa.Column('session_topic', sa.String(length=250), nullable=False),
    sa.Column('session_date', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mentor_bookings')
    # ### end Alembic commands ###
