"""Create skill exchanges table

Revision ID: fa8f49cd0da9
Revises: 9fa24df16480
Create Date: 2026-08-15 23:16:27.132855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8f49cd0da9'
down_revision = '9fa24df16480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=150), nullable=False),
    sa.Column('student_email', sa.String(length=200), nullable=False),
    sa.Column('skill_offered', sa.String(length=150), nullable=False),
    sa.Column('skill_wanted', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('availability', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_exchanges')
    # ### end Alembic commands ###
